name: Deploy to Netlify

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build with Gatsby
      run: npm run build

    - name: Create deploy branch
      run: |
        git checkout -b deploy
        git add public
        git commit -m "Deploy build files"
        git push --force origin deploy
